name: Deploy to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production   # ensures environment secrets are available

    permissions:
      contents: read

    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Install functions deps
        working-directory: functions
        run: npm install --no-audit --no-fund

      - name: Prepare SSR assets
        run: |
          rm -rf functions/.next
          cp -R .next functions/.next

      - name: Choose auth method
        id: choose-auth
        run: |
          if [ -n "${FIREBASE_SERVICE_ACCOUNT}" ]; then
            echo "method=service_account" >> $GITHUB_OUTPUT
            echo "Using service account authentication"
          elif [ -n "${FIREBASE_TOKEN}" ]; then
            echo "method=firebase_token" >> $GITHUB_OUTPUT
            echo "Using Firebase CI token authentication"
          else
            echo "No auth credentials available. Set FIREBASE_SERVICE_ACCOUNT or FIREBASE_TOKEN secrets."
            exit 1
          fi

      - name: Authenticate to Google Cloud
        if: steps.choose-auth.outputs.method == 'service_account'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.FIREBASE_SERVICE_ACCOUNT }}
          export_environment_variables: true

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy Hosting and Functions (service account)
        if: steps.choose-auth.outputs.method == 'service_account'
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: |
          firebase deploy --only hosting,functions --project ${{ env.FIREBASE_PROJECT_ID }} --non-interactive

      - name: Deploy Hosting and Functions (CI token)
        if: steps.choose-auth.outputs.method == 'firebase_token'
        env:
          FIREBASE_TOKEN: ${{ env.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: |
          firebase deploy --only hosting,functions --project ${{ env.FIREBASE_PROJECT_ID }} --non-interactive
